### ISSUE TITLE
V0.3 feedback

### ISSUE THREAD

**Issue by chanjunweimy** [CS2103JAN2017-F14-B2/main#97]
Team,

Good job in the demo! This is some reviews about your V0.3 documents! :) (p/s: I realized sinyi is not in the organization, can you all fix this?

## User Guide
* Help: how about ppl typing "man"? It stands for manual in Unix.
* hmmm actually, what happened if people type help add, for example??
* What is the downside of implementing listdone, listnotdone, listtag all as commands? You need to create all of them as a class? There are great coding pattern that we can follow instead! (Ex: list done, list not done, ... ) Do you see the difference?
* FAQ: KIT should work with any computer with java 8 installed? :P
* The 'Command summary' section will be used heavily by our testers. Try to make it easy to use as possible. e.g. give examples for each command.
* In future, you might want to use partial screenshots capturing only the part in concern. Having screenshots of certain command as an example of the output of the UI would always be better. ^^ However, you might want to put partial screenshot if not changing the whole UI would give you a lot of work. :P

## Developer Guide
* Note that in a UML diagram, dotted line means dependency whereas a solid line means association, see: http://stackoverflow.com/questions/26982886/uml-relationships-dashed-line-vs-solid-line So do not confuse about the use of them! 
* Wrong word! Do spell check! 
![image](https://cloud.githubusercontent.com/assets/7464833/24339474/4fc95a62-12de-11e7-81c2-9276ba8f7d3a.png)
* Good job in explaining about the implementation of undo/redo!
* It may be more practical to give a few examples of interesting test cases and explain the thinking behind how you arrived at those test cases, rather than try to give a comprehensive list of all test cases.

Overall, you all did a good job! Good work!

Your tutor,
Jun Wei

**Comment by mlemzing** [comment]
@chanjunweimy @XinyiYS is in the organisation but he has set the visibility to private.
